// JavaScript Document

var catalogs2 = {
    type: [
        {id: 11, name: '电子教材'},
        {id: 12, name: '课件'},
        {id: 13, name: '微课'},
        {id: 14, name: '教学游戏'},
        {id: 15, name: '教学案例'},
        {id: 16, name: '活动方案'},
        {id: 17, name: '教学工具'},
        {id: 18, name: '教学素材'}
    ],
    subject: [
        {id: 21, name: '语文'},
        {id: 22, name: '英语'},
        {id: 23, name: '数学'},
        {id: 24, name: '物理'},
        {id: 25, name: '化学'},
        {id: 26, name: '生物'},
        {id: 27, name: '政治'},
        {id: 28, name: '历史'}
    ],
    stage: [
        {id: 31, name: '小学一年级'},
        {id: 32, name: '小学二年级'},
        {id: 33, name: '小学三年级'},
        {id: 34, name: '小学四年级'},
        {id: 35, name: '小学五年级'},
        {id: 36, name: '小学六年级'},
        {id: 37, name: '初一'},
        {id: 38, name: '初二'},
        {id: 39, name: '初三'}
    ],
    version: [
        {id: 41, name: '人教版'},
        {id: 42, name: '首师大'},
        {id: 43, name: '北京版'},
        {id: 44, name: '北师版'}
    ]
};
var _stages = [
    {id: 1, caption: '小学一年级'},
    {id: 2, caption: '小学二年级'},
    {id: 3, caption: '小学三年级'},
    {id: 4, caption: '小学四年级'},
    {id: 5, caption: '小学五年级'},
    {id: 6, caption: '小学六年级'},
    {id: 7, caption: '初一'},
    {id: 8, caption: '初二'},
    {id: 9, caption: '初三'},
    {id: 10, caption: '高一'},
    {id: 11, caption: '高二'},
    {id: 12, caption: '高三'}
]
var catalogs = {
    type: ['电子教材', '课件', '微课', '教学游戏', '教学案例', '活动方案', '教学工具', '教学素材'],
    subject: ['语文', '英语', '数学', '物理', '化学', '生物', '政治', '历史', '地理', '科学', '品德与生活', '音乐', '美术', '体育与健康', '历史与社会', '信息技术'],
    stage: ['小学一年级', '小学二年级', '小学三年级', '小学四年级', '小学五年级', '小学六年级', '初一', '初二', '初三'],
    version: ['人教版', '首师大', '北京版', '北师版']
};

var resources = [
    {
        "id": "1",
        "author": "刘华",
        "type": "电子教材",
        "subject": "英语",
        "region": "大兴区", <!--所属区域-->
        "stage2": "小学",
        "stage": "小学三年级",
        "version": "北京版",
        "photo": "images/electronMaterial/1.jpg",
        "name": "英语"
    },
    {
        "id": "2",
        "author": "黄菲",
        "type": "电子教材",
        "subject": "物理",
        "region": "东城区",
        "stage": "初二",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/electronMaterial/2.jpg",
        "name": "物理",
        "mediaType": 2,
        "mediaUrl": 'media/内燃机.mp4'
    },
    {
        "id": "3",
        "author": "张合",
        "type": "电子教材",
        "subject": "化学",
        "region": "房山区",
        "stage2": "初中",
        "stage": "初三",
        "stage2": "初中",
        "version": "沪教版",
        "photo": "images/electronMaterial/3.jpg",
        "name": "化学",
        "mediaType": 2,
        "mediaUrl": 'media/用过氧化氢制备氧气.mp4'

    },
    {
        "id": "4",
        "author": "焦飞",
        "type": "电子教材",
        "subject": "数学",
        "region": "房山区",
        "stage2": "小学",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/electronMaterial/4.jpg",
        "name": "数学"

    },
    {
        "id": "5",
        "author": "程飞",
        "type": "电子教材",
        "subject": "数学",
        "region": "东城区",
        "stage": "初一",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/electronMaterial/5.jpg",
        "name": "数学"

    },
    {
        "id": "6",
        "author": "韩贝",
        "type": "电子教材",
        "subject": "英语",
        "region": "海淀区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/electronMaterial/6.jpg",
        "name": "英语"

    },
    {
        "id": "7",
        "author": "朱画",
        "type": "电子教材",
        "subject": "语文",
        "region": "海淀区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/electronMaterial/7.jpg",
        "name": "语文"

    },
    {
        "id": "8",
        "author": "李吉",
        "type": "电子教材",
        "subject": "美术",
        "region": "大兴区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/electronMaterial/8.jpg",
        "name": "美术"

    },
    {
        "id": "9",
        "author": "王一",
        "type": "电子教材",
        "subject": "音乐",
        "region": "通州区",
        "stage": "小学一年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/electronMaterial/9.jpg",
        "name": "音乐"

    },
    {
        "id": "10",
        "author": "程飞",
        "type": "电子教材",
        "subject": "数学",
        "region": "通州区",
        "stage": "初三",
        "stage2": "初中",
        "version": "沪教版",
        "photo": "images/electronMaterial/10.jpg",
        "name": "数学"

    },
    {
        "id": "11",
        "author": "刘华",
        "type": "电子教材",
        "subject": "英语",
        "region": "朝阳区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/electronMaterial/11.jpg",
        "name": "英语"

    },
    {
        "id": "12",
        "author": "金帅",
        "type": "电子教材",
        "subject": "英语",
        "region": "朝阳区",
        "stage": "初一",
        "stage2": "初中",
        "version": "首师大",
        "photo": "images/electronMaterial/12.jpg",
        "name": "英语"

    },
    {
        "id": "13",
        "author": "佚名",
        "type": "电子教材",
        "subject": "生物",
        "region": "大兴区",
        "stage": "初一",
        "stage2": "初中",
        "version": "首师大",
        "photo": "images/electronMaterial/13.jpg",
        "name": "生物"

    },
    {
        "id": "14",
        "author": "刘斐",
        "type": "电子教材",
        "subject": "地理",
        "region": "通州区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/electronMaterial/14.jpg",
        "name": "地理"

    },
    {
        "id": "15",
        "author": "张合",
        "type": "电子教材",
        "subject": "历史",
        "region": "房山区",
        "stage": "初三",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/electronMaterial/15.jpg",
        "name": "历史"

    },
    {
        "id": "16",
        "author": "腾辉",
        "type": "电子教材",
        "subject": "美术",
        "region": "海淀区",
        "stage": "初一",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/electronMaterial/16.jpg",
        "name": "美术"

    },
    {
        "id": "17",
        "author": "黄菲",
        "type": "电子教材",
        "subject": "思想品德",
        "region": "朝阳区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/electronMaterial/17.jpg",
        "name": "思想品德"

    },
    {
        "id": "18",
        "author": "焦海",
        "type": "电子教材",
        "subject": "体育与健康",
        "region": "大兴区",
        "stage": "初一",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/electronMaterial/18.jpg",
        "name": "体育与健康"

    },
    {
        "id": "19",
        "author": "黄菲",
        "type": "电子教材",
        "subject": "品德与社会",
        "region": "昌平区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/electronMaterial/19.jpg",
        "name": "品德与社会"

    },
    {
        "id": "20",
        "author": "王一",
        "type": "电子教材",
        "subject": "化学",
        "region": "昌平区",
        "stage": "初三",
        "stage2": "初中",
        "version": "首师大",
        "photo": "images/electronMaterial/20.jpg",
        "name": "化学"

    },
    {
        "id": "34",
        "type": "微课",
        "subject": "历史",
        "region": "大兴区",
        "author": "刘斐",
        "stage": "初一",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/class/24.jpg",
        "name": "中国历史"

    },
    {
        "id": "21",
        "type": "微课",
        "subject": "数学",
        "region": "昌平区",
        "author": "佚名",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/class/11.jpg",
        "name": "圆的认识"

    },
    {
        "id": "22",
        "type": "微课",
        "subject": "品德与生活",
        "region": "大兴区",
        "author": "王一",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/class/12.jpg",
        "name": "沙漠中的绿洲"

    },
    {
        "id": "23",
        "type": "微课",
        "subject": "数学",
        "region": "朝阳区",
        "author": "刘华",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/class/13.jpg",
        "name": "数数与计数"

    },
    {
        "id": "24",
        "type": "微课",
        "subject": "历史",
        "region": "房山区",
        "author": "泛舟",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/class/14.jpg",
        "name": "腾飞的中国"

    },
    {
        "id": "25",
        "type": "微课",
        "subject": "科学",
        "region": "通州区",
        "author": "腾辉",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "人教社",
        "photo": "images/class/15.jpg",
        "name": "动物"

    },
    {
        "id": "26",
        "type": "微课",
        "subject": "品德与生活",
        "region": "昌平区",
        "author": "韩贝",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/class/16.jpg",
        "name": "北京"

    },
    {
        "id": "28",
        "type": "微课",
        "subject": "语文",
        "region": "东城区",
        "author": "程飞",
        "stage": "初一",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/class/18.jpg",
        "name": "济南的冬天"

    },
    {
        "id": "30",
        "type": "微课",
        "subject": "英语",
        "region": "朝阳区",
        "author": "巴特",
        "stage": "初一",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/class/20.jpg",
        "name": "Sports"

    },
    {
        "id": "32",
        "type": "微课",
        "subject": "化学",
        "region": "房山区",
        "author": "李菲",
        "stage2": "初中",
        "stage": "初三",
        "version": "北师版",
        "photo": "images/class/22.jpg",
        "name": "常见的酸和碱"

    },
    {
        "id": "33",
        "type": "微课",
        "subject": "思想品德",
        "region": "朝阳区",
        "author": "盛名",
        "stage": "初一",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/class/23.jpg",
        "name": "真爱生命"

    },
    {
        "id": "35",
        "type": "微课",
        "subject": "地理",
        "region": "海淀区",
        "author": "朱画",
        "stage": "初一",
        "stage2": "初中",
        "version": "沪教版",
        "photo": "images/class/25.jpg",
        "name": "澳大利亚"

    },
    {
        "id": "36",
        "type": "微课",
        "subject": "品德与社会",
        "region": "大兴区",
        "author": "应采",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "沪教版",
        "photo": "images/class/26.jpg",
        "name": "好大一个家"

    },
    {
        "id": "37",
        "type": "微课",
        "subject": "数学",
        "region": "海淀区",
        "author": "黄菲",
        "stage": "初一",
        "stage2": "初中",
        "version": "沪教版",
        "photo": "images/class/27.jpg",
        "name": "有理数与整式加减"

    },
    {
        "id": "38",
        "type": "微课",
        "subject": "生物",
        "region": "朝阳区",
        "author": "张合",
        "stage": "初一",
        "stage2": "初中",
        "version": "人教社",
        "photo": "images/class/28.jpg",
        "name": "开花和结果"

    },
    {
        "id": "39",
        "type": "微课",
        "subject": "地理",
        "region": "大兴区",
        "author": "金帅",
        "stage": "初二",
        "stage2": "初中",
        "version": "人教社",
        "photo": "images/class/29.jpg",
        "name": "英国及爱尔兰"

    },
    {
        "id": "40",
        "type": "微课",
        "subject": "历史",
        "region": "昌平区",
        "author": "李吉",
        "stage": "初一",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/class/30.jpg",
        "name": "繁荣的隋唐"

    },


    {
        "id": "230",
        "author": "程飞",
        "type": "教学工具",
        "subject": "物理",
        "region": "大兴区",
        "stage2": "初中",
        "stage": "初一",
        "version": "北京版",
        "photo": "images/tool/g7.jpg",
        "name": "弹簧秤",
        "updateTime": "2014-3-28",
        "description": " "

    },
    {
        "id": "231",
        "author": "黄宏",
        "type": "教学工具",
        "subject": "化学",
        "region": "大兴区",
        "stage2": "初中",
        "stage": "初二",
        "version": "北京版",
        "photo": "images/tool/g6.jpg",
        "name": "量筒和烧杯",
        "updateTime": "2014-3-28",
        "description": ""

    },
    {
        "id": "232",
        "author": "程飞",
        "type": "教学工具",
        "subject": "生物",
        "region": "大兴区",
        "stage2": "初中",
        "stage": "初二",
        "version": "北京版",
        "photo": "images/tool/g5.jpg",
        "name": "显微镜",
        "updateTime": "2014-3-28",
        "description": "本软件可计算圆曲线带有缓和曲线中、边桩坐标及切线方位角，若只需计算圆曲线则缓和曲线输入0即可。 2、附有正算、反算功能，正算：通过里程和偏距计算坐标，反算：通过坐标反推里程和偏距。3、数据输入：曲线转角α和计算方位角F按d.ms格式输入 4、具有数据导入、导出功能，可把已知数据输入在文本文档中进行导入，导出则是把已经输入好的数据导出到指定位置。5、数据处理完毕后点击“保存数据”可进行保存曲线五大桩、曲线参数表，连续计算模式“保存数据”可导出计算成果。"

    },
    {
        "id": "233",
        "author": "李静",
        "type": "教学工具",
        "subject": "信息技术",
        "region": "大兴区",
        "stage2": "小学",
        "stage": "小学三年级",
        "version": "人教版",
        "photo": "images/tool/g4.jpg",
        "name": "圆规",
        "updateTime": "2014-3-28",
        "description": " 1.附有正算、反算功能，正算：通过里程和偏距计算坐标，反算：通过坐标反推里程和偏距。3、数据输入：曲线转角α和计算方位角F按d.ms格式输入 "

    },
    {
        "id": "234",
        "author": "李飞",
        "type": "教学工具",
        "subject": "语文",
        "region": "大兴区",
        "stage2": "小学",
        "stage": "小学四年级",
        "version": "北京版",
        "photo": "images/tool/g2.jpg",
        "name": "新华字典",
        "updateTime": "2014-3-28",
        "description": " "

    },
    {
        "id": "235",
        "author": "程飞",
        "type": "教学工具",
        "subject": "英语",
        "region": "大兴区",
        "stage2": "小学",
        "stage": "小学三年级",
        "version": "北京版",
        "photo": "images/tool/g3.jpg",
        "name": "小学英汉词典",
        "updateTime": "2014-3-28",
        "description": ""
    },
    {
        "id": "236",
        "author": "程飞",
        "type": "教学工具",
        "subject": "语文",
        "region": "大兴区",
        "stage2": "小学",
        "stage": "小学二年级",
        "version": "北京版",
        "photo": "images/tool/g1.jpg",
        "name": "小学谚语词典",
        "updateTime": "2014-3-28",
        "description": ""

    },
    {
        "id": "42",
        "author": "李吉",
        "type": "教学工具",
        "subject": "物理",
        "region": "东城区",
        "stage": "初二",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/courseware/w4.jpg",
        "name": "物理",
        "updateTime": "2011-12-28",
        "description": "小巧易用，是同类软件中体积最小、功能最强大的。无需安装，不写注册表，纯绿色软件。功能强大，加载速度快。数据准确、全面。完善的演示功能，适合课堂演示。独创元素记忆游戏，令学习更轻松。方程式配平工具采用复合算法，针对不同的方程式采用不同的算法，运算速度远远超越目前同类软件。"
    },
    {
        "id": "43",
        "author": "朱画",
        "type": "教学工具",
        "subject": "物理",
        "region": "东城区",
        "stage": "初二",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/courseware/w3.jpg",
        "name": "物理",
        "updateTime": "2011-12-22",
        "description": "金华科在仿真物理实验室和数理平台之后的又一力作.仿真化学实验室包括：化学仿真实验平台、三维化学分子模型和化学资料中心。在化学仿真实验平台中您可以自由的搭建实验仪器、添加药品，并让它进行反应。它不但有逼真的现象还能为您提供准确的实验数据。三维化学分子模型可以为您展示奇妙的微观化学世界。它不但可以展示石墨、金刚石、NaCl等晶体结构，还可以让您十分轻松的搭建出各种有机分子的微观模型。化学资料中心是以元素周期表为总线的化学资料库，您可以利用它十分方便的查找出您所关心的化学信息，并可以让您把这些信息以网页的格式输出。您还可以自由的修改和添加您所需要的资料。"
    },
    {
        "id": "44",
        "author": "金帅",
        "type": "教学工具",
        "subject": "化学",
        "region": "房山区",
        "stage": "初三",
        "stage2": "初中",
        "version": "沪教版",
        "photo": "images/sourceMaterial/17.jpg",
        "name": "化学",
        "updateTime": "2011-12-29",
        "description": "使用本软件绘制二维、二维半、三维函数图形、动画和表数据图形。主要特色罗列如下：1. 二维图形函数形式可以是显式、参数形式、隐式或不等式；直角坐标系和极坐标系；函数图形动画；反函数的图形；导函数的图形；函数的奇偶性；极大值、极小值和拐点；积分；根；弧长；切线和法线；曲率圆；二维曲线的交点；相交区域的面积；基于表数据的二维线形图；散点图；曲线平滑；阶梯图；火柴杆图；采用了消锯齿技术，曲线平滑度高。2. 二维半图形函数形式可以是显式和参数形式；直角坐标系和极坐标系；函数图形动画；基于表数据的带形图。3. 三维图形函数形式可以是显式和参数形式；直角坐标系、柱面坐标系和球面坐标系；三维曲线和曲面；三维曲线和曲面动画；基于表数据的三维曲面；基于二维曲线的旋转曲面；材质和光照；顶点、线框和曲面模型；高质量的图形效果。4. 创建色谱图、等值线图和矢量图。5. 设置和修改图形和动画的属性。6. 平移、缩小、放大和旋转生成的图形########7. 将生成的图形保存为pgp和bmp文件。8. 将动画保存为 AVI 文件9. 免费工具 数学计算器等"
    },
    {
        "id": "45",
        "author": "韩贝",
        "type": "教学工具",
        "subject": "数学",
        "region": "房山区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/tool/5.jpg",
        "name": "小学数学伴侣",
        "updateTime": "2012-4-10",
        "description": "《小学数学伴侣》内容覆盖小学数学1～6年级全部章节，深入浅出，各个学习模块均以寓教于乐的方式进行。软件与教材（人教版、苏教版）同步，所有题目都严格筛选，并且类型丰富、难易适当(含数学竞赛题)，题目启发性非常强，软件操作性相当人性化……整个软件的设计，真正从小朋友学习数学的兴趣出发，着重培养小朋友学数学的兴趣，锻炼数学逻辑思维、创新意识、速算能力、想象与推理……"
    },
    {
        "id": "46",
        "author": "焦海",
        "type": "教学工具",
        "subject": "信息技术",
        "region": "海淀区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/tool/6.jpg",
        "name": "疯狂的数字",
        "updateTime": "2011-12-31",
        "description": "《疯狂的数字》是一款专门为小学生设计的数学学习软件，主要分为数学专项训练和数学游戏两大模块。寓教于乐，使学习数学过程不再枯燥，在不知不觉中提高分析、口算、速算能力。"
    },
    {
        "id": "47",
        "author": "韩贝",
        "type": "教学工具",
        "subject": "信息技术",
        "region": "海淀区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/tool/7.jpg",
        "name": "几何图霸播放器",
        "updateTime": "2013-7-8",
        "description": "?播放器主要用于打开《几何图霸》制作的课件，供中学数学老师教学时使用，完全免费。欲制作课件，请下载《几何图霸》软件。?"
    },
    {
        "id": "48",
        "author": "王一",
        "type": "教学工具",
        "subject": "信息技术",
        "region": "大兴区",
        "author": "王一",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/tool/8.jpg",
        "name": "化学",
        "updateTime": "2011-12-22",
        "description": "该软件是专门为化学工作者定制基于WORD平台的一套专业排版辅助软件，利用该软件可以轻松实现化学中常用的同位素输入、原子结构示意图、电子式、电子转移标注、有机物结构式、有机反应方程式、反应条件输入、化学常用符号输入、化学仪器、化学装置、图片图形调整等许多实用功能功能，同时该软件还提供一套方便易用的题库系统。独创的化学文章输入窗口，更是将该软件的功能发挥到极致！在该窗口中输入化学式，化学方程式，离子方程式时，完全不用考虑大小写和上下标问题，全部由软件中的强大的智能识别替换系统自动完成！！！经测试，利用该软件制作化学试题比普通方法节约时间20～50！指法越快节约时间越明显。实在是化学工作者的不可多得的梦幻工具！"
    },
    {
        "id": "50",
        "author": "李吉",
        "type": "教学工具",
        "subject": "信息技术",
        "region": "东城区",
        "stage": "小学一年级",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/tool/10.jpg",
        "name": "Adobe Reader",
        "updateTime": "2014-5-20",
        "description": "adobe reader官方下载版(也称为Acrobat Reader)是美国Adobe公司开发的一款优秀的PDF文档阅读软件。文档的撰写者可以向任何人分发自己制作(通过Adobe Acobat制作)的PDF文档而不用担心被恶意篡改。Adobe Reader XI.（adobe reader官方下载版）最大的亮点是PDF文档将可以与Office文档实现相互转换，进行无缝对接。"
    },
    {
        "id": "51",
        "author": "金帅",
        "type": "教学工具",
        "subject": "信息技术",
        "region": "东城区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/tool/11.jpg",
        "name": "新华字典词典",
        "updateTime": "2013-12-17",
        "description": "该软件可能是目前网上最好的辞典软件。全面收集最新版本的新华字典16159条汉字、新华词典371834条词语、现代成语词典31847条成语、现代歇后语辞典14028条歇后语、大英汉辞典36672条语词翻译、古今名人22992条名言录。不断升级，精彩无限。是一个精巧、全面、新颖的桌面资料工具。软件收集了中国所有的国标汉字，所有的规范成语，全面收集，权威、科学。是一个优秀的学习工具助手。新华字典包括汉字拼音、笔划、部首、检字法、五笔编码，字源、组词、举例、意思等等。详尽、齐全、细致、深入。成语词典包括拼音、出处、举例等等。歇后语典包括前部分及后部分。新华字典、成语词典、歇后语典都包括模糊检索功能。方便、快捷、高效。软件同时集成了众多的资料，包括名人名言、对联、名句欣赏、魔鬼词典、绕口令、千字文、三字经、百家姓、昔时贤文、俗语、谚语等等。是一款不可多得的优秀工具软件。"
    },
    {
        "id": "52",
        "author": "程飞",
        "type": "教学工具",
        "subject": "化学",
        "region": "东城区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/sourceMaterial/18.jpg",
        "name": "化学",
        "updateTime": "2013-12-18",
        "description": "'我爱学拼音2.0'是在'我爱学拼音1.0'的基础上的全面升级改版。它增加了两种学习方式，结合儿童喜爱卡通动画的心理特点，采用卡通动画的方式，结合听、说、读、写等训练，寓教于乐。本软件互动性极强，儿童运用本软件，跟随小恐龙，在听故事、玩游戏中不知不觉地就学会了拼音达到自己能看拼音故事的水平。是2-9岁儿童学拼音的最佳多媒体软件。经测试，本软件对儿童认知能力、计算机操作能力、思维想象能力都有一定提高！"
    },
    {
        "id": "53",
        "author": "张合",
        "type": "教学工具",
        "subject": "信息技术",
        "region": "大兴区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/tool/13.jpg",
        "name": "汉字笔顺精灵",
        "updateTime": "2010-2-19",
        "description": "汉字笔顺精灵是专为那些初学汉字笔顺的人设计的，尤其适合小学低年级的小朋友学习使用。它将小学一年级语文的每个生字的笔顺进行直观、形象的书写演示， 生动、有趣，寓教于乐，加深记忆，便于准确地写出规范的汉字笔顺。同时，还给出每个生字的注音、组词、笔画数，是学习汉字生字的好伙伴。"
    },

    {
        "id": "56",
        "author": "腾辉",
        "type": "课件",
        "subject": "语文",
        "region": "朝阳区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/case/2.jpg",
        "name": "乡下人家",
        "updateTime": "2014-5-22",
        "description": ""
    },
    {
        "id": "57",
        "author": "佚名",
        "type": "课件",
        "subject": "英语",
        "region": "大兴区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/case/3.jpg",
        "name": "A Transution Point in My Life",
        "updateTime": "2014-5-23",
        "description": "课件中主要想小朋友们讲解，A Transution Point in My Life。"
    },
    {
        "id": "58",
        "author": "王一",
        "type": "课件",
        "subject": "英语",
        "region": "海淀区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/case/4.jpg",
        "name": "看图识单词",
        "updateTime": "2014-5-20",
        "description": "看图片识别对应的英语单词，有趣形象。"
    },
    {
        "id": "63",
        "author": "焦海",
        "type": "课件",
        "subject": "语文",
        "region": "东城区",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "苏教版",
        "photo": "images/case/1.jpg",
        "name": "三打白骨精",
        "updateTime": "2014-5-21",
        "description": "在一个古树参天、绿草如茵的森林里,有一群自由的鹿。可是,最近不知从哪儿来了一群狼,经常来骚扰,鹿群里的鹿都很惊慌,"
    },
    {
        "id": "59",
        "author": "李吉",
        "type": "课件",
        "subject": "语文",
        "region": "昌平区",
        "stage2": "初中",
        "stage": "初一",
        "version": "北师版",
        "photo": "images/case/5.jpg",
        "name": "翠鸟",
        "updateTime": "2014-5-27",
        "description": "",

    },
    {
        "id": "60",
        "author": "朱画",
        "type": "课件",
        "subject": "美术",
        "region": "东城区",
        "stage": "小学五年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/case/6.png",
        "name": "英语大闯关",
        "updateTime": "2014-5-20",
        "description": "生动形象，趣味十足。"

    },
    {
        "id": "61",
        "author": "金帅",
        "type": "课件",
        "subject": "历史",
        "region": "海淀区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/case/7.jpg",
        "name": "丝绸之路",
        "updateTime": "2014-5-20",
        "description": "中国历史悠久，从盘古、女娲、后羿等神话时代算起约有5000年；从三皇五帝算起约有4600年；自夏朝算起约有近4100年；从中国第一次大统一的中央集权制的秦朝算起约有2200年。"
    },
    {
        "id": "62",
        "author": "朱画",
        "type": "课件",
        "subject": "英语",
        "region": "东城区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/case/8.png",
        "name": "趣味学英语1",
        "updateTime": "2014-5-29",
        "description": "本课件共分15部分，包括英语语音、英语幽默、故事、谜语、绕口令、谚语、英语游戏，诗歌、词语掌故、演讲、知识竞赛、短剧等内容。"
    },
    {
        "id": "64",
        "author": "张合",
        "type": "课件",
        "subject": "物理",
        "region": "东城区",
        "stage": "初一",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/case/9.jpg",
        "name": "物理",
        "updateTime": "2014-5-29",
        "description": "天平的使用"
    },
    {
        "id": "65",
        "author": "韩贝",
        "type": "课件",
        "subject": "英语",
        "region": "东城区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/case/10.jpg",
        "name": "快乐学英语1",
        "updateTime": "2014-5-29",
        "description": "本书共分15部分，包括英语语音、英语幽默、故事、谜语、绕口令、谚语、英语游戏，诗歌、词语掌故、演讲、知识竞赛、短剧等内容。"
    },
    {
        "id": "66",
        "author": "佚名",
        "type": "课件",
        "subject": "英语",
        "region": "海淀区",
        "stage": "小学五年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/case/11.jpg",
        "name": "快乐学英语1",
        "updateTime": "2014-5-29",
        "description": "本书共分15部分，包括英语语音、英语幽默、故事、谜语、绕口令、谚语、英语游戏，诗歌、词语掌故、演讲、知识竞赛、短剧等内容。"
    },
    {
        "id": "67",
        "author": "黄菲",
        "type": "课件",
        "subject": "美术",
        "region": "朝阳区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/case/12.jpg",
        "name": "快乐学英语1",
        "updateTime": "2014-5-29",
        "description": "本书共分15部分，包括英语语音、英语幽默、故事、谜语、绕口令、谚语、英语游戏，诗歌、词语掌故、演讲、知识竞赛、短剧等内容。"
    },
    {
        "id": "69",
        "author": "李吉",
        "type": "课件",
        "subject": "美术",
        "region": "朝阳区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/case/14.jpg",
        "name": "初中美术欣赏",
        "updateTime": "2014-5-29",
        "description": "九年义务教育全日制初级中学化学教学大纲(试用修订版) 课程与教材 听课与评课 走进新教材 探究教学"
    },
    {
        "id": "70",
        "author": "焦海",
        "type": "课件",
        "subject": "化学",
        "region": "朝阳区",
        "stage": "初三",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/case/15.jpg",
        "name": "化学1",
        "updateTime": "2014-5-29",
        "description": "九年义务教育全日制初级中学化学教学大纲(试用修订版) 课程与教材 听课与评课 走进新教材 探究教学"
    },
    {
        "id": "71",
        "author": "张合",
        "type": "教学案例",
        "subject": "数学",
        "region": "东城区",
        "stage": "小学五年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/courseware/1.jpg",
        "name": "小学教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "72",
        "author": "焦海",
        "type": "教学案例",
        "subject": "音乐",
        "region": "朝阳区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/courseware/2.jpg",
        "name": "小学音乐教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。"
    },
    {
        "id": "72",
        "author": "腾辉",
        "type": "教学案例",
        "subject": "数学",
        "region": "大兴区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "人教社",
        "photo": "images/courseware/14.jpg",
        "name": "小学语文教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "73",
        "author": "刘华",
        "type": "教学案例",
        "subject": "英语",
        "region": "东城区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/courseware/4.jpg",
        "name": "初中英语教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "74",
        "author": "金帅",
        "type": "教学案例",
        "subject": "数学",
        "region": "昌平区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/courseware/5.jpg",
        "name": "小学数学教学案例",
        "updateTime": "2014-5-27",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "75",
        "author": "刘华",
        "type": "教学案例",
        "subject": "语文",
        "region": "东城区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/courseware/3.jpg",
        "name": "小学语文教学案例",
        "updateTime": "2014-5-24",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "82",
        "author": "韩贝",
        "type": "教学案例",
        "subject": "语文",
        "region": "东城区",
        "stage": "初三",
        "stage2": "初中",
        "version": "首师大",
        "photo": "images/courseware/14.jpg",
        "name": "初中语文教学案例",
        "updateTime": "2014-3-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "84",
        "author": "李吉",
        "type": "教学案例",
        "subject": "化学",
        "region": "海淀区",
        "stage": "初一",
        "stage2": "初中",
        "version": "首师大",
        "photo": "images/courseware/16.jpg",
        "name": "初中化学教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "85",
        "author": "王一",
        "type": "教学案例",
        "subject": "物理",
        "region": "东城区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/courseware/w1.jpg",
        "name": "初中物理教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "86",
        "author": "黄菲",
        "type": "教学案例",
        "subject": "化学",
        "region": "昌平区",
        "stage": "小学一年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/courseware/17.jpg",
        "name": "初中化学教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "87",
        "author": "韩贝",
        "type": "教学案例",
        "subject": "物理",
        "region": "东城区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/courseware/w2.jpg",
        "name": "初中物理教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "76",
        "author": "程飞",
        "type": "教学案例",
        "subject": "数学",
        "region": "大兴区",
        "stage": "小学五年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/courseware/7.jpg",
        "name": "小学数学教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "77",
        "author": "朱画",
        "type": "教学案例",
        "subject": "英语",
        "region": "东城区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/courseware/8.jpg",
        "name": "小学英语教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "78",
        "author": "金帅",
        "type": "教学案例",
        "subject": "物理",
        "region": "东城区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/courseware/9.jpg",
        "name": "小学物理教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "79",
        "author": "王一",
        "type": "教学案例",
        "subject": "语文",
        "region": "东城区",
        "stage": "初三",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/courseware/10.jpg",
        "name": "初中语文教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "80",
        "author": "张合",
        "type": "教学案例",
        "subject": "数学",
        "region": "朝阳区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/courseware/11.jpg",
        "name": "小学数学教学案例",
        "updateTime": "2014-5-20",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },
    {
        "id": "81",
        "author": "刘斐",
        "type": "教学案例",
        "subject": "语文",
        "region": "东城区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/courseware/13.jpg",
        "name": "初中语文作文教学案例",
        "updateTime": "2014-5-28",
        "description": "用爱去教育,用情感管理。 初中学生要比小学生生更懂得爱,更需要关心，爱护"
    },


    {
        "id": "210",
        "author": "张合",
        "type": "活动方案",
        "subject": "品德与生活",
        "region": "东城区",
        "stage": "小学五年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/activityProgram/h1.jpg",
        "name": "教学活动研讨会"
    },
    {
        "id": "211",
        "author": "张宝",
        "type": "活动方案",
        "subject": "品德与生活",
        "region": "东城区",
        "stage": "初一",
        "stage2": "初中",
        "version": "首师大",
        "photo": "images/activityProgram/h2.jpg",
        "name": "实践活动教学"
    },
    {
        "id": "212",
        "author": "马良",
        "type": "活动方案",
        "subject": "品德与生活",
        "region": "东城区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/activityProgram/h3.jpg",
        "name": "数学研讨会"
    },
    {
        "id": "213",
        "author": "马良",
        "type": "活动方案",
        "subject": "品德与生活",
        "region": "东城区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/activityProgram/h4.jpg",
        "name": "小学英语活动方案研讨会"
    },
    {
        "id": "214",
        "author": "李良",
        "type": "活动方案",
        "subject": "品德与生活",
        "region": "东城区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/activityProgram/h5.jpg",
        "name": "小学语文活动方案研讨会"
    },
    {
        "id": "89",
        "author": "刘斐",
        "type": "活动方案",
        "subject": "语文",
        "region": "东城区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/activityProgram/2.jpg",
        "name": "漫游语文世界",
        "downUrl": "media/设计活动方案.ppt"
    },

    {
        "id": "95",
        "author": "刘华",
        "type": "活动方案",
        "subject": "生物",
        "region": "房山区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/activityProgram/8.jpg",
        "name": "生物学教学"
    },
    {
        "id": "96",
        "author": "张合",
        "type": "活动方案",
        "subject": "生物",
        "region": "通州区",
        "stage": "初三",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/activityProgram/9.jpg",
        "name": "细胞生物学"
    },
    {
        "id": "97",
        "author": "王一",
        "type": "活动方案",
        "subject": "历史",
        "region": "通州区",
        "stage": "小学一年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/activityProgram/10.jpg",
        "name": "祖国在我心"
    },
    {
        "id": "98",
        "author": "佚名",
        "type": "活动方案",
        "subject": "历史",
        "region": "通州区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "沪教版",
        "photo": "images/activityProgram/11.jpg",
        "name": "60周年"
    },
    {
        "id": "99",
        "author": "焦海",
        "type": "活动方案",
        "subject": "历史与社会",
        "region": "通州区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/activityProgram/12.jpg",
        "name": "回望历史手抄报"
    },
    {
        "id": "102",
        "author": "金帅",
        "type": "活动方案",
        "subject": "地埋",
        "region": "朝阳区",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/activityProgram/15.jpg",
        "name": "学业导航"
    },
    {
        "id": "103",
        "author": "焦飞",
        "type": "活动方案",
        "subject": "英语",
        "region": "朝阳区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/activityProgram/16.jpg",
        "name": "我爱记单词"
    },
    {
        "id": "104",
        "author": "韩贝",
        "type": "活动方案",
        "subject": "英语",
        "region": "海淀区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/activityProgram/17.jpg",
        "name": "英语沙龙"
    },
    {
        "id": "105",
        "author": "腾辉",
        "type": "活动方案",
        "subject": "英语",
        "region": "海淀区",
        "stage": "初三",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/activityProgram/18.jpg",
        "name": "英语夏令营"
    },
    {
        "id": "106",
        "author": "金帅",
        "type": "活动方案",
        "subject": "数学",
        "region": "海淀区",
        "stage": "小学一年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/activityProgram/19.jpg",
        "name": "数学节"
    },
    {
        "id": "107",
        "author": "王一",
        "type": "活动方案",
        "subject": "数学",
        "region": "海淀区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/activityProgram/20.jpg",
        "name": "摸球游戏"
    },
    {
        "id": "108",
        "author": "佚名",
        "type": "活动方案",
        "subject": "数学",
        "region": "大兴区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "人教社",
        "photo": "images/activityProgram/21.jpg",
        "name": "第四届数学周"
    },

    {
        "id": "112",
        "type": "教学素材",
        "author": "赵欣",
        "subject": "英语",
        "region": "昌平区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/sourceMaterial/s1.jpg",
        "name": "小学英语"
    },
    {
        "id": "114",
        "author": "赵杰",
        "type": "教学素材",
        "subject": "历史与社会",
        "region": "海淀区",
        "stage": "初三",
        "stage2": "初中",
        "version": "首师大",
        "photo": "images/sourceMaterial/s2.jpg",
        "name": "关注教育"
    },
    {
        "id": "115",
        "author": "钱多多",
        "type": "教学素材",
        "subject": "历史与社会",
        "region": "海淀区",
        "stage2": "小学",
        "stage": "小学一年级",
        "version": "首师大",
        "photo": "images/sourceMaterial/s5.jpg",
        "name": "启迪未来"
    },
    {
        "id": "116",
        "author": "钱国良",
        "type": "教学素材",
        "subject": "语文",
        "region": "海淀区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/sourceMaterial/s3.jpg",
        "name": "儒家思想 仁"
    },
    {
        "id": "117",
        "author": "钱萍",
        "type": "教学素材",
        "subject": "语文",
        "region": "通州区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/sourceMaterial/s4.jpg",
        "name": "儒家思想 仁义"
    },
    {
        "id": "118",
        "author": "孙易",
        "type": "教学素材",
        "subject": "音乐",
        "region": "通州区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/sourceMaterial/s6.jpg",
        "name": "关爱儿童"
    },
    {
        "id": "119",
        "author": "孙晓晓",
        "type": "教学素材",
        "subject": "美术",
        "region": "通州区",
        "stage": "小学五年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/sourceMaterial/s7.jpg",
        "name": "中国水墨画"
    },
    {
        "id": "120",
        "author": "孙子茹",
        "type": "教学素材",
        "subject": "美术",
        "region": "房山区",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/sourceMaterial/s8.jpg",
        "name": "中国水墨画"
    },
    {
        "id": "121",
        "author": "李果",
        "type": "教学素材",
        "subject": "生物",
        "region": "房山区",
        "stage": "初一",
        "stage2": "初中",
        "version": "首师大",
        "photo": "images/sourceMaterial/10.jpg",
        "name": "生物"
    },
    {
        "id": "122",
        "author": "李丽",
        "type": "教学素材",
        "subject": "英语",
        "region": "房山区",
        "stage": "初二",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/sourceMaterial/11.jpg",
        "name": "英语"
    },
    {
        "id": "123",
        "author": "李悦",
        "type": "教学素材",
        "subject": "英语",
        "region": "朝阳区",
        "stage": "初三",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/sourceMaterial/12.jpg",
        "name": "英语"
    },
    {
        "id": "124",
        "author": "吴炎炎",
        "type": "教学素材",
        "subject": "品德与生活",
        "region": "朝阳区",
        "stage2": "小学",
        "stage": "小学一年级",
        "version": "人教版",
        "photo": "images/sourceMaterial/13.jpg",
        "name": "品德与生活"
    },
    {
        "id": "127",
        "author": "郑新",
        "type": "教学素材",
        "subject": "数学",
        "region": "东城区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/sourceMaterial/16.jpg",
        "name": "数学"
    },
    {
        "id": "128",
        "author": "王一一",
        "type": "教学素材",
        "subject": "化学",
        "region": "东城区",
        "stage": "小学五年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/sourceMaterial/17.jpg",
        "name": "化学"
    },
    {
        "id": "129",
        "author": "王娟",
        "type": "教学素材",
        "subject": "化学",
        "region": "大兴区",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "首师大",
        "photo": "images/sourceMaterial/18.jpg",
        "name": "化学"
    },
    {
        "id": "130",
        "author": "冯可心",
        "type": "教学素材",
        "subject": "地理",
        "region": "大兴区",
        "stage": "初一",
        "stage2": "初中",
        "version": "人教版",
        "photo": "images/sourceMaterial/19.jpg",
        "name": "地理"
    },
    {
        "id": "131",
        "author": "陈宁",
        "type": "教学素材",
        "subject": "生物",
        "region": "大兴区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/sourceMaterial/20.jpg",
        "name": "生物"
    },
    {
        "id": "201",
        "author": "李浩",
        "type": "教学游戏",
        "subject": "品德与生活",
        "region": "海淀区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/z1.jpg",
        "name": "积木",
        "updateTime": "2013-11-15",
        "description": "锻炼孩子的动手能力和平衡能力"
    },
    {
        "id": "200",
        "author": "李斯",
        "type": "教学游戏",
        "subject": "品德与生活",
        "region": "海淀区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/z2.jpg",
        "name": "安全常识",
        "updateTime": "2013-11-15",
        "description": "在游戏中让孩子们学会安全常识"
    },
    {
        "id": "203",
        "author": "王浩",
        "type": "教学游戏",
        "subject": "品德与生活",
        "region": "海淀区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/z3.jpg",
        "name": "篮球课",
        "updateTime": "2013-11-15",
        "description": "让孩子们从小热爱运动，喜欢篮球"
    },
    {
        "id": "204",
        "author": "王凯",
        "type": "教学游戏",
        "subject": "品德与生活",
        "region": "海淀区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/z5.jpg",
        "name": "拉环",
        "updateTime": "2013-11-15",
        "description": "锻炼孩子的动手能力和平衡能力"
    },
    {
        "id": "205",
        "author": "李晟",
        "type": "教学游戏",
        "subject": "品德与生活",
        "region": "朝阳区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/z4.jpg",
        "name": "妈妈与孩子",
        "updateTime": "2013-11-15",
        "description": "锻炼孩子的动手能力和学习能力"
    },
    {
        "id": "206",
        "author": "李浩",
        "type": "教学游戏",
        "subject": "品德与生活",
        "region": "海淀区",
        "stage": "小学五年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/z6.jpg",
        "name": "气球",
        "updateTime": "2013-11-15",
        "description": "让孩子们在快乐中学习，锻炼孩子的动手能力和平衡能力"
    },
    {
        "id": "207",
        "author": "李浩",
        "type": "教学游戏",
        "subject": "品德与生活",
        "region": "海淀区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/z7.jpg",
        "name": "滑板",
        "updateTime": "2013-11-15",
        "description": "滑板"
    },
    {
        "id": "208",
        "author": "李浩",
        "type": "教学游戏",
        "subject": "品德与生活",
        "region": "海淀区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/z8.jpg",
        "name": "积木",
        "updateTime": "2013-11-15",
        "description": "锻炼孩子的协调能力和平衡能力"
    },
    {
        "id": "133",
        "author": "张美",
        "type": "教学游戏",
        "subject": "信息技术",
        "region": "大兴区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/3.png",
        "name": "化学教学",
        "updateTime": "2010-10-12",
        "description": "这个小女孩正在上她最不擅长的化学课，而她的化学老师又是一个非常严厉的人，你要帮助这个小女孩不在她的老师面前出错。"
    },
    {
        "id": "134",
        "author": "韩信",
        "type": "教学游戏",
        "subject": "数学",
        "region": "房山区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/game/4.png",
        "name": "课堂教学",
        "updateTime": "2010-11-4",
        "description": "学校的师资资源现在非常紧缺，每个老师都需要同时负责好几个班级的课程，你能坚持多久呢？赶快来试试吧！"
    },
    {
        "id": "135",
        "author": "王菲",
        "type": "教学游戏",
        "subject": "信息技术",
        "region": "朝阳区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/game/5.png",
        "name": "朵拉教学",
        "updateTime": "2010-12-2",
        "description": "小朵拉除了是一名冒险家，原来她还是一名出色的老师。今天，朵拉要教你学两种语言。有兴趣来学习一下吗？"
    },
    {
        "id": "136",
        "author": "张辉",
        "type": "教学游戏",
        "subject": "物理",
        "region": "大兴区",
        "stage": "初三",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/game/6.png",
        "name": "教室找物品",
        "updateTime": "2011-11-15",
        "description": "教室里隐藏着很多有趣的东西，需要发挥观察力才找的到哦！找对了就可以加分，错了可是要减分的~看看你能找对多少得多少分吧！"
    },
    {
        "id": "137",
        "author": "邵佳",
        "type": "教学游戏",
        "subject": "化学",
        "region": "通州区",
        "stage": "初二",
        "stage2": "初中",
        "version": "北师版",
        "photo": "images/game/7.png",
        "name": "教你学写诗",
        "updateTime": "2007-5-22",
        "description": "学诗并不是很难，你玩了这个游戏就会明白。不信就来试一试吧！"
    },
    {
        "id": "138",
        "author": "韩斌",
        "type": "教学游戏",
        "subject": "历史",
        "region": "海淀区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/game/8.png",
        "name": "教你学单词",
        "updateTime": "2007-5-10",
        "description": "游乐场出现了好多个单词哦，大家一起来学习吧！"
    },
    {
        "id": "139",
        "author": "王静",
        "type": "教学游戏",
        "subject": "地理",
        "region": "朝阳区",
        "stage": "小学五年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/9.png",
        "name": "熊孩子识字",
        "updateTime": "2014-1-3",
        "description": "《熊孩子识字》系列是一款学习汉字的好帮手，每个字以动画的形式展示，内容包括字、词、句，生动形象并可拓展孩子的思维，适用于2-8岁的孩子。每次一课，5个字5个故事，轻松愉悦中学习！"
    },
    {
        "id": "140",
        "author": "丹华",
        "type": "教学游戏",
        "subject": "生物",
        "region": "通州区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/game/10.png",
        "name": "猪猪侠汉字英雄",
        "updateTime": "2013-10-22",
        "description": "聪明的猪猪侠来了，他带着许多的文学小知识还有小常识，考考我们聪明的小朋友们，现在让我们一起来接受猪猪侠的挑战吧！看我们小朋友谁最聪明哦！"
    },
    {
        "id": "141",
        "author": "冰河",
        "type": "教学游戏",
        "subject": "生物",
        "region": "大兴区",
        "stage2": "小学",
        "stage": "小学一年级",
        "version": "首师大",
        "photo": "images/game/11.png",
        "name": "中国文化小测验",
        "updateTime": "2013-8-8",
        "description": "中国文化博大精深，光是我们从小学的历史及国文课本就可以迭到不知道多高了，但是长大后是不是都忘个精光了呢，没关系我们现在就来做个小测验，看看那时拼死命背的东西有没有都还给老师了呢？"
    },
    {
        "id": "142",
        "author": "康盛",
        "type": "教学游戏",
        "subject": "地理",
        "region": "房山区",
        "stage": "小学三年级",
        "stage2": "小学",
        "version": "沪教版",
        "photo": "images/game/12.png",
        "name": "中华礼仪教育委员会",
        "updateTime": "2013-8-6",
        "description": "中华礼仪教育委员会：礼仪是塑造形象的重要手段，在社会活动中，交谈讲究礼仪，可以变得文明；举止讲究礼仪可以变得高雅；穿着讲究礼仪，可以变得大方；行为讲究礼仪，可以变得美好……只要讲究礼仪，事情都会做的恰到好处。总之一个人讲究礼仪，就可以变得充满魅力！据说玩过此游戏的人幸福指数会高于常人哦，信不信由你"
    },
    {
        "id": "143",
        "author": "李芬",
        "type": "教学游戏",
        "subject": "生物",
        "region": "东城区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "北师版",
        "photo": "images/game/13.png",
        "name": "人体结构拼图",
        "updateTime": "2012-8-15",
        "description": "对于自己的身体结构你了解多少呢？你知道，心脏，胃，肝脏等器官都在身体的什么位置上么？如果不知道，就来学习学习吧，认识下这些都是什么，在什么位置吧！"
    },
    {
        "id": "144",
        "author": "张飞",
        "type": "教学游戏",
        "subject": "历史与社会",
        "region": "东城区",
        "stage2": "小学",
        "stage": "小学一年级",
        "version": "人教版",
        "photo": "images/game/14.png",
        "name": "中国地图之省份",
        "updateTime": "2011-11-20",
        "description": "你所居住在地球上的那个国家呢？中国？嘿嘿！那你在哪个省呢？一款益智学习小游戏——中国地图之省份。你能正确辨认出自己的省市在中国地图上的准确位置么？快来挑战下吧！看看你有没有好好上学，嘿嘿！"
    },
    {
        "id": "145",
        "author": "刘备",
        "type": "教学游戏",
        "subject": "数学",
        "region": "东城区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/game/15.png",
        "name": "奇妙算数",
        "updateTime": "2011-8-23",
        "description": "奇妙算数，一款儿童学习类小游戏。如果你把乘法表背的滚瓜烂熟，又熟悉各种纸牌玩法，比如：算24点等小游戏的话。你可以来挑战下这款算数游戏，难度还是比较高的哦，快来体验下头脑风暴吧！嘿嘿！"
    },
    {
        "id": "146",
        "author": "广裕",
        "type": "教学游戏",
        "subject": "英语",
        "region": "东城区",
        "stage2": "初中",
        "stage": "初二",
        "version": "北师版",
        "photo": "images/game/16.png",
        "name": "泡泡乘法",
        "updateTime": "2008-1-29",
        "description": "一个数学乘法的测试，用键盘输入乘积按回车键就可以把泡泡消了！"
    },
    {
        "id": "147",
        "author": "刘安",
        "type": "教学游戏",
        "subject": "英语",
        "region": "大兴区",
        "stage2": "小学",
        "stage": "小学一年级",
        "version": "沪教版",
        "photo": "images/game/17.jpg",
        "name": "趣味数学题",
        "updateTime": "2010-12-4",
        "description": "一款有趣的数学游戏，根据加减乘除得到目标的值就能过关。游戏内有详细的中文教学说明。来试试吧"
    },
    {
        "id": "148",
        "author": "窦赢",
        "type": "教学游戏",
        "subject": "语文",
        "region": "海淀区",
        "stage": "小学二年级",
        "stage2": "小学",
        "version": "北京版",
        "photo": "images/game/18.png",
        "name": "认识形状",
        "updateTime": "2014-5-15",
        "description": "小朋友们，游戏中的形状都认识吗？赶快把他们拖入相应的图片中吧！对了，相应图片的颜色也要涂对哦！"
    },
    {
        "id": "149",
        "author": "华锁",
        "type": "教学游戏",
        "subject": "体育与健康",
        "region": "朝阳区",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "沪教版",
        "photo": "images/game/19.png",
        "name": "地震如何自救",
        "updateTime": "2013-4-26",
        "description": "地震如何自救：正在上课，地震发生了，你知道该怎么办吗？帮游戏的的同学顺利到操场躲避吧！每一步都很重要，做出错误的决断会断送性命！游戏不是给大家玩的，主要目的是教大家地震躲避常识，大家要认真学习哦.."
    },
    {
        "id": "150",
        "author": "郑德军",
        "type": "教学游戏",
        "subject": "数学",
        "region": "昌平区",
        "stage": "小学四年级",
        "stage2": "小学",
        "version": "人教版",
        "photo": "images/game/20.png",
        "name": "巧虎的铁道之旅",
        "updateTime": "2013-3-12",
        "description": "今天，巧虎全家要做火车去旅行，小朋友跟巧虎一起出发吧。先买好车票，然后不能弄错坐车的时间，最后记住沿途火车都到过哪里，巧虎会考考你哦~"
    },
    {
        "id": "151",
        "author": "华丰",
        "type": "教学游戏",
        "subject": "语文",
        "region": "东城区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/game/1.png",
        "name": "英语大闯关",
        "updateTime": "2013-9-10",
        "description": "我们的口号是：拒绝枯燥，《英语大闯关》让你玩着学英文！不坑爹，不耗费流量，离线也能轻松学英文！"
    },
    {
        "id": "152",
        "author": "华丰",
        "type": "教学游戏",
        "subject": "政治",
        "region": "东城区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/game/s1.jpg",
        "name": "政治",
        "updateTime": "2013-9-10",
        "description": "我们的口号是：拒绝枯燥，《英语大闯关》让你玩着学英文！不坑爹，不耗费流量，离线也能轻松学英文！"
    },
    {
        "id": "153",
        "author": "华丰",
        "type": "教学游戏",
        "subject": "政治",
        "region": "东城区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/game/s2.jpg",
        "name": "政治",
        "updateTime": "2013-9-10",
        "description": "我们的口号是：拒绝枯燥，《英语大闯关》让你玩着学英文！不坑爹，不耗费流量，离线也能轻松学英文！"
    },
    {
        "id": "154",
        "author": "华丰",
        "type": "教学游戏",
        "subject": "政治",
        "region": "东城区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/game/s3.jpg",
        "name": "政治",
        "updateTime": "2013-9-10",
        "description": "我们的口号是：拒绝枯燥，《英语大闯关》让你玩着学英文！不坑爹，不耗费流量，离线也能轻松学英文！"
    },
    {
        "id": "155",
        "author": "华丰",
        "type": "教学游戏",
        "subject": "政治",
        "region": "东城区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/game/s4.jpg",
        "name": "政治",
        "updateTime": "2013-9-10",
        "description": "我们的口号是：拒绝枯燥，《英语大闯关》让你玩着学英文！不坑爹，不耗费流量，离线也能轻松学英文！"
    },
    {
        "id": "157",
        "author": "华丰",
        "type": "教学游戏",
        "subject": "政治",
        "region": "东城区",
        "stage": "初一",
        "stage2": "初中",
        "version": "北京版",
        "photo": "images/game/s6.jpg",
        "name": "政治",
        "updateTime": "2013-9-10",
        "description": "我们的口号是：拒绝枯燥，《英语大闯关》让你玩着学英文！不坑爹，不耗费流量，离线也能轻松学英文！"
    },
    {
        "id": "158",
        "author": "华锁",
        "type": "教学游戏",
        "subject": "科学",
        "region": "朝阳区",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "沪教版",
        "photo": "images/game/k1.jpg",
        "name": "地震如何自救",
        "updateTime": "2013-4-26",
        "description": "地震如何自救：正在上课，地震发生了，你知道该怎么办吗？帮游戏的的同学顺利到操场躲避吧！每一步都很重要，做出错误的决断会断送性命！游戏不是给大家玩的，主要目的是教大家地震躲避常识，大家要认真学习哦.."
    },
    {
        "id": "159",
        "author": "华锁",
        "type": "教学游戏",
        "subject": "科学",
        "region": "朝阳区",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "沪教版",
        "photo": "images/game/k2.jpg",
        "name": "地震如何自救",
        "updateTime": "2013-4-26",
        "description": "地震如何自救：正在上课，地震发生了，你知道该怎么办吗？帮游戏的的同学顺利到操场躲避吧！每一步都很重要，做出错误的决断会断送性命！游戏不是给大家玩的，主要目的是教大家地震躲避常识，大家要认真学习哦.."
    },
    {
        "id": "160",
        "author": "华锁",
        "type": "教学游戏",
        "subject": "科学",
        "region": "朝阳区",
        "stage": "小学六年级",
        "stage2": "小学",
        "version": "沪教版",
        "photo": "images/game/k3.jpg",
        "name": "地震如何自救",
        "updateTime": "2013-4-26",
        "description": "地震如何自救：正在上课，地震发生了，你知道该怎么办吗？帮游戏的的同学顺利到操场躲避吧！每一步都很重要，做出错误的决断会断送性命！游戏不是给大家玩的，主要目的是教大家地震躲避常识，大家要认真学习哦.."
    }
]
$(function () {
    if (!localStorage.resources)
        localStorage.resources = JSON.stringify(resources);
    resources = JSON.parse(localStorage.resources);
})
function getResourceById(id) {
    var result = resources.find({id: id});
    if (result.length > 0)
        return result[0];
    return null;
}
function getResources(c, sc) {
    var filter = {};
    filter[c] = sc;
    return resources.find(filter);
}

function getBystage(stageName) {
    return resources.find({stage: stageName});
}

function getBySubject(subject) {
    return resources.find({subject: subject});
}

function getByVersion(versionName) {
    return resources.find({version: version});
}

function getByRegion(regionName) {
    return resources.find({region: regionName});
}

function getByType(typeName) {
    return resources.find({type: typeName});
}
